version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    ports:
      - "8080:8080"
      - "50000:50000"

  nexus:
    image: sonatype/nexus3:latest
    restart: always
    ports:
      - "8081:8081"
